# Generated by Django 6.0 on 2026-01-12 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_review_ratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='description',
            new_name='comments',
        ),
    ]
