# Generated by Django 6.0 on 2026-01-12 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_date_review_created_at_review_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
    ]
