# Generated by Django 6.0 on 2026-01-12 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_created_at_product_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='review',
            name='updated_at',
        ),
    ]
