# Generated by Django 6.0 on 2026-01-21 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_review_created_at_review_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
