# Generated by Django 6.0 on 2026-01-14 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Not paid', 'Not Paid'), ('Ready to ship', 'Ready To Ship'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('canceled', 'Canceled')], default='Not paid', max_length=20),
        ),
    ]
